### ISSUE TITLE
真是太好玩辣

### ISSUE THREAD

**Issue by LinXueyuanStdio** [futantan/OpenGpt#12]
https://open-gpt.app/app/clf3bhs46000el608tgvki05f

![网页捕获_11-3-2023_95852_open-gpt app](https://user-images.githubusercontent.com/23211526/224460961-bc41a22e-0abe-4934-94bd-a1df1e84c844.jpeg)
![网页捕获_11-3-2023_101323_open-gpt app](https://user-images.githubusercontent.com/23211526/224460962-10af5933-7a39-4dd2-89c0-dd77b241f77e.jpeg)
![网页捕获_11-3-2023_101643_open-gpt app](https://user-images.githubusercontent.com/23211526/224460964-afe1a37b-4d58-4140-aac6-7c26a724af4c.jpeg)
![网页捕获_11-3-2023_102338_open-gpt app](https://user-images.githubusercontent.com/23211526/224460966-171c1e39-6ef4-4686-9f91-b995dbc261bf.jpeg)
![网页捕获_11-3-2023_104017_open-gpt app](https://user-images.githubusercontent.com/23211526/224460967-205fb53e-ec1a-46db-8dd4-28d29e752e7c.jpeg)
![网页捕获_11-3-2023_10359_open-gpt app](https://user-images.githubusercontent.com/23211526/224460968-a23e6089-98e1-4c9f-b723-77b6a07c8f54.jpeg)
![网页捕获_11-3-2023_10559_open-gpt app](https://user-images.githubusercontent.com/23211526/224460969-aa889b77-d6a0-4362-9092-5d4f2faf11a0.jpeg)

**Comment by futantan** [comment]
哇！太有意思啦！
可以在 twitter 或者其他社交媒体上推荐，并 tag 我！（https://twitter.com/EclipsePrayer）

感谢你的分享，但 issue 更多是用来记录问题，我会在今天稍晚的时候，关闭这个 issue，也请你理解呀~

**Comment by LinXueyuanStdio** [comment]
理解理解！
