### ISSUE TITLE
proposal: 创建出的应用有多个输入框

### ISSUE THREAD

**Issue by seeflood** [futantan/OpenGpt#2]
## 需求
允许创建出的应用有多个输入框。

一个很好的例子是 https://app.prompthub.studio/prompt/259f3a75-3d6b-4753-a709-7ce8b997a894
这是一个”写邮件“app，它有多个输入框（收件人、主题、消息）
![image](https://user-images.githubusercontent.com/26001097/224059925-0199ba5f-a877-4796-aab8-9206ecaec296.png)

## 实现方案
- 每个应用创建时，可以按需选择自己有几个输入框；
- prompt 里可以使用 `${Recipent}` 这样的形式来引用不同输入框的内容

**Comment by futantan** [comment]
有多个输入框是一个不错的信息输入模式，但也同时会给用户使用造成负担。
以上面写邮件为例，可以在 prompt 中告知，会有 收件人、主题、消息
并在输入中，明确指明即可。

在后期可能会考虑这种方式，但是目前会尽量保持简洁

**Comment by KeJunMao** [comment]
我用vue 实现了一个支持的
https://github.com/KeJunMao/ai-anything
