### ISSUE TITLE
📝 文档改善 

### ISSUE THREAD

**Issue by tiwentichat** [futantan/OpenGpt#21]
# 文档改善建议 📝

小白瑟瑟发抖：这个要怎么部署啊。。

## 您的建议是什么？ 🤔

请简要描述您的文档改善建议，包括您的目标和想法。

如果您的建议是解决某个特定问题的，请尽可能提供更多的上下文和细节。

## 您的建议有哪些优势？ 🌟

请简要描述您的建议的优势和特点，比如：

- 是否可以提高文档的可读性和易用性？
- 是否可以使文档更加详细和准确？
- 是否可以让文档更好地反映项目的实际情况？

感谢您的分享和支持！🙏

**Comment by Leizhenpeng** [comment]
这个repo基本是t3的脚手架搭起来的，

这里有一些参考资料给你~

- [t3](https://create.t3.gg/zh-hans)
- [trpc](https://trpc.io/)
- [next.js](https://nextjs.org/learn/foundations/about-nextjs?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=next-website)

**Comment by futantan** [comment]
项目部署在 Vercel 上，只需要配置好环境变量即可。
数据库需要选用一个支持 serverless 的数据库。

我可能陷入了“专家陷阱”，因为我有全部的上下文，所以没能了解的你的具体问题。
等你问题全部解决后，请帮忙提个 PR 完善 Readme

**Comment by tiwentichat** [comment]
> 这个repo基本是t3的脚手架搭起来的，
> 
> 这里有一些参考资料给你~
> 
> * [t3](https://create.t3.gg/zh-hans)
> * [trpc](https://trpc.io/)
> * [next.js](https://nextjs.org/learn/foundations/about-nextjs?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=next-website)

好的，typescript第一次接触，我先学习下，感谢。

**Comment by tiwentichat** [comment]
> 项目部署在 Vercel 上，只需要配置好环境变量即可。 数据库需要选用一个支持 serverless 的数据库。
> 
> 我可能陷入了“专家陷阱”，因为我有全部的上下文，所以没能了解的你的具体问题。 等你问题全部解决后，请帮忙提个 PR 完善 Readme

我代码会的不多，用过一些python开源的代码，会告知执行什么代码，我都是git clone后纯按教程操作完成的 - -！

按照你这个提醒，我刚用vercl试了一下，是直接创建新项目、把git里面的repo复制进去deploy吗？

环境变量需要设置什么内容？没找到数据库的设置选项（或许这算是我的问题..
