### ISSUE TITLE
🚀 功能改善 - 保存api的反馈提示

### ISSUE THREAD

**Issue by Leizhenpeng** [futantan/OpenGpt#42]
# 功能改善建议 🚀

usage页面

保存本地api成功后没有任何交互反馈，

## 您的建议是什么？ 🤔

为了提高用户体验，建议在保存本地 API 成功后添加一个交互反馈提示。

例如： 弹出一个对话框或者在界面上显示一个成功的提示信息。

这可以让用户知道他们的操作已经成功完成，同时也可以减少用户的不必要疑虑和焦虑。

![image](https://user-images.githubusercontent.com/50035229/224678558-337c4867-4a6c-4736-870a-3bed60c829fe.png)

感谢您的分享和支持！🙏

**Comment by futantan** [comment]
Done. thank you!
