### ISSUE TITLE
🚀 功能改善 - 替换限制ip改为浏览器指纹

### ISSUE THREAD

**Issue by Leizhenpeng** [futantan/OpenGpt#49]
# 功能改善建议 🚀

我们发现有些用户可能会使用反向代理或公共路由器，这可能会导致我们的服务端误判你的IP地址，影响到你的使用体验。
而且，在不少公司的WiFi下层，用户第一次使用时可能会遇到付费提醒，无法体验服务。

## 您的建议是什么？ 🤔

为了更准确地识别你的设备，提供更好的服务体验，我们建议使用浏览器指纹识别技术，它可以更精准地识别你的设备，避免上述问题的发生。

**Comment by futantan** [comment]
ip 限制主要是为了限制成本，这里的限制包括两部分：
1. 普通用户，用户量过多，不得不限制
2. 对于一些滥用 api 的人

对于 2，不清楚能否组织那些滥用 api 的人，这是目前的一个担忧

**Comment by Leizhenpeng** [comment]
mature consideration ~
