### ISSUE TITLE
📝 文档改善  添加ContributionGuide

### ISSUE THREAD

**Issue by sherry0429** [futantan/OpenGpt#51]
没有指南如何本地运行repo，
把这个指南给出来可以让PR多一些

顺便想问问看源码没有看出来后端是什么，看上去，是直接nodejs跑起来的server？

**Comment by BarrySong97** [comment]
nextjs，本身就是一个全栈框架，也就是ssr，也就是你说的node跑起来的server

**Comment by futantan** [comment]
谢谢 @BarrySong97 的回答。
这是一个标准的 NextJS 项目，对于 NextJS 部分的内容，请参考官网文档。
