### ISSUE TITLE
Add Multi Language Functionality [ Enhancement ]

### ISSUE THREAD

**Issue by CodeWizarz** [futantan/OpenGpt#62]
# Could you guys Please add Support for English Language so that other users can understand.
## its a request though :)

**Comment by futantan** [comment]
hi @CodeWizarz we actually added i18n before, but it contains some tricky bug that only happen in production environment.
https://github.com/futantan/OpenGpt/pull/33

will try to fix it and bring it back soon. It will be great if you can help to move this forward

**Comment by CodeWizarz** [comment]
@futantan Yea I don't mind lending a hand :|

**Comment by CodeWizarz** [comment]
![Screenshot from 2023-03-15 21-42-02](https://user-images.githubusercontent.com/122372759/225371835-2a8cdfe8-02d0-4b51-a80c-129f62355b9e.png)
 does this look satisying :|

**Comment by futantan** [comment]
you are so quick!
Let's skip the UI part and only focus on the i18n mechanism. to keep it simple, only need to add i18n into the project.

For the UI part, I'm still thinking of a solution：
- a dropdown in the. header menu
- maybe we need to isolate apps  different languages from each other

**Comment by CodeWizarz** [comment]
> you are so quick!
> Let's skip the UI part and only focus on the i18n mechanism. to keep it simple, only need to add i18n into the project.
> 
> For the UI part, I'm still thinking of a solution：
> - a dropdown in the. header menu
> - maybe we need to isolate apps  different languages from each other

I tried it (i18n) but it sort of doesn't seem to fit into the project structure yet i have added the package and created jsons for languages en.json and zh.json in root dir and I'm unable to wrap the whole layout in index.tsx with i18n but I'll figure it out XD. I'll continue working on it from tomorrow morning. And i have disabled database functionality just for instance :⁠^⁠) and as for UI u have used tailwind so it'll be quite easy.

**Comment by futantan** [comment]
https://github.com/futantan/OpenGpt/pull/72
