### ISSUE TITLE
📝 因为您的微信被添加过于频繁，想要与您取得联系

### ISSUE THREAD

**Issue by Evani300** [futantan/OpenGpt#67]
我在一家一线基金任职一直寻找AIGC Infra层/应用层的人才，和百位来自Meta,OpenAl, Stability，Google,等公司的华人学者做过交流,加您希望能向您学习您的研究方向，一起探索商业化的可能性,我们也对任何合作的可能保持开放的态度,希望这几天能约您一个时间我们沟通一下。这是我的微信：c13559870609。迫切想与您联系！

**Comment by futantan** [comment]
暂不考虑，谢谢
